version: "3.8"
services:
  masquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
        - 1883:1883
        - 9001:9001
    volumes:
        - ./mosquitto/data/:/mosquitto/data
        - ./mosquitto/log/:/mosquitto/log
        - ./mosquitto/config/:/mosquitto/config
    restart: unless-stopped
